import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import Chatbot from "./Chatbot"; // provjeri da je putanja ispravna

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="font-sans min-h-screen flex flex-col items-center gap-10 w-full">
          <Header />
          <main className="w-full max-w-5xl px-4">{children}</main>
          
          {/* Chatbot */}
          <Chatbot />
        </div>
      </body>
    </html>
  );
}
