import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="font-sans h-screen flex flex-col items-center gap-10">
          <nav className="flex justify-between items-center p-6 bg-gray-100 w-full">
            <Link href="/">
              <h1 className="text-3xl font-bold">Loto Aplikacija</h1>
            </Link>

            <div className="flex items-center justify-center gap-4">
              <button type="submit" className="px-4 py-2 bg-blue-500 text-white rounded">
                <a href="/auth/login">Prijava</a>
              </button>
            </div>
          </nav>

          {children}
        </div>
      </body>
    </html>
  );
}
